id = "comment"
name = "Comment"
version = "0.2.0"
schema_version = 1
authors = ["Donnie Adams <donnie@thedadams.com>"]
description = "Comment language extension"
repository = "https://github.com/thedadams/zed-comment"

[grammars.comment]
repository = "https://github.com/thedadams/tree-sitter-comment"
rev = "93dd14b58334dd66591ebc62b1e5a91168cc302c"
