id = "comment"
name = "Comment"
version = "0.3.1"
schema_version = 1
authors = ["Donnie Adams <donnie@thedadams.com>"]
description = "Comment language extension"
repository = "https://github.com/thedadams/zed-comment"

[grammars.comment]
repository = "https://github.com/thedadams/tree-sitter-comment"
rev = "1036b75112fe0e751a6a659496f954b70cccaf48"
