id = "comment"
name = "Comments Highlighter"
version = "0.6.7"
schema_version = 1
authors = ["Donnie Adams <donnie@thedadams.com>"]
description = "Comment language extension for highlighting special comments"
repository = "https://github.com/thedadams/zed-comment"

[grammars.comment]
repository = "https://github.com/thedadams/tree-sitter-comment"
rev = "66272d2b6c73fb61157541b69dd0a7ce7b42a5ad"
