on:
  push:
    tags:
      - "v*"

jobs:
  homebrew:
    name: Release Zed Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate version matches tag
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          TOML_VERSION=$(grep '^version = ' extension.toml | sed 's/version = "\(.*\)"/\1/')

          if [ "$TAG_VERSION" != "$TOML_VERSION" ]; then
            echo "Error: Tag version (v$TAG_VERSION) does not match extension.toml version ($TOML_VERSION)"
            exit 1
          fi

          echo "Version validation passed: $TAG_VERSION"

      - uses: huacnlee/zed-extension-action@v1
        with:
          extension-name: comment
          push-to: thedadams/zed-extensions
        env:
          # the personal access token should have "repo" & "workflow" scopes
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
